### ISSUE TITLE
Why not use 2.pool.ntp.org? That one has IPv6.

### ISSUE THREAD

**Issue by mdavids** [FreeRTOS/coreSNTP#45]
Why not use 2.pool.ntp.org here? Especially handy in IPv6-only environments, because this one is (at the moment) the only pool-server with an AAAA-record. 

Chrony on CentOS8 or Android have done this too, among others.

https://github.com/FreeRTOS/coreSNTP/blob/7d835d59fd4f5c2e08186e7ec013f65bb0d6c78f/docs/doxygen/code_examples/example_sntp_client_posix.c#L173

**Comment by aggarw13** [comment]
Hi @mdavids, sorry about the delay in responding. 
The use of `0.pool.ntp.org` in the example code is just one example of a time server that can be used to configure the coreSNTP library for querying time from. It is not intended to be a recommendation to users about choice of the NTP server. The primary purpose of the [example_sntp_client_posix.c](https://github.com/FreeRTOS/coreSNTP/blob/main/docs/doxygen/code_examples/example_sntp_client_posix.c) file is just to showcase how the library API can be used to setup an SNTP client. The library can be configured to use **ANY** time server, whether publicly available time service like NTP Pool or a privately owned NTP server.  We will add a comment in the file to clarify the point.

**Comment by gshvang** [comment]
PR has been merged for the issue. Hence closing the issue.
