### ISSUE TITLE
Version in manifest.yml is not aligned with tag.

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [FreeRTOS/coreSNTP#67]
![image](https://user-images.githubusercontent.com/16876353/191560671-caac677f-8668-4a5e-956d-a9f4f833c3f0.png)
https://github.com/FreeRTOS/coreSNTP/blob/v1.1.0/manifest.yml

**Comment by johnrhen** [comment]
Thanks for bringing this issue to our attention, we're looking into it now.

**Comment by kstribrnAmzn** [comment]
@DavidJurajdaNXP we've discussed this and our plan is release a commit fixing this and retag the v1.1.0 tag to this commit. I'm hoping to get time today to do this. I'll follow up on this Issue once I've completed the work.

**Comment by kstribrnAmzn** [comment]
Fixed this now! You should be able to see that the [v1.1.0 release](https://github.com/FreeRTOS/coreSNTP/releases/tag/v1.1.0) has the correct manifest.yml version number.

I'm going to close this as this issue should be resolved.
