### ISSUE TITLE
Not all status codes are handled in Sntp_StatusToStr() function

### ISSUE THREAD

**Issue by eeFLis** [FreeRTOS/coreSNTP#82]
Not all cases of `SntpStatus_t `status codes are handled in `Sntp_StatusToStr`.
Therefore `Sntp_StatusToStr` returns "Invalid status code!" also for valid states such as SntpRejectedResponse,SntpErrorSendTimeout
etc.

**Comment by aggarg** [comment]
Thank you for reporting this. The following PR address it - https://github.com/FreeRTOS/coreSNTP/pull/83.
