### ISSUE TITLE
On the DoxyGen docs, SntpLeapSecondInfo_t table has mismatched descriptions.

### ISSUE THREAD

**Issue by IvanVeloz** [FreeRTOS/coreSNTP#91]
On the DoxyGen documentation, the table on the `SntpLeapSecondInfo_t` enum has mismatched names and descriptions.

For example, the `LastMinuteHas61Seconds` enum is described as "There is no upcoming leap second adjustment.".

https://freertos.github.io/coreSNTP/main/group__sntp__enum__types.html#ga69e2cb17ab4e253491602ccfe48b141f

Thank you for this great library.

Ivan

**Comment by aggarg** [comment]
Thank you for reporting this. The following PR addresses it - https://github.com/FreeRTOS/coreSNTP/pull/92.
